version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5003 wsgi:app
    volumes:
      - .:/app
    ports:
      - "5003:5003"
    environment:
      - FLASK_ENV=production
