services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5002 wsgi:app
    volumes:
      - .:/app
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=production
      - PORT=5003
      - CONSUL_HOST=consul
      - FLASK_ENV=development
      - MYSQL_HOST=mysql-service
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DB=order_db
    depends_on:
      - mysql-service
      - redis-service
    networks:
      - microservices-net
